#!/usr/bin/env python3

import threading
from threading import Thread, Lock
from pprint import pprint

from termcolor import colored

import targetPages

accounts_to_test = ['katia_managon', 'theCryingCat']

print_lock = Lock()
thread_handlers = []

def job_check_and_print(page):
    result = page.check_result(accounts_to_test)

    print_lock.acquire()

    print('')
    print(page.site_name)
    print('=====')
    for r in result:
        text = "%s: %s" % (
                r[0],
                colored('True', 'green') if r[1] else colored('False', 'red'))

        print(text)

    print_lock.release()

thread_handlers = list(
        map(lambda page: Thread(target=job_check_and_print, args=(page,)),
            targetPages.all_pages)
        )

for handler in thread_handlers:
    handler.start()

for handler in thread_handlers:
    handler.join()
