#!/usr/bin/env python3

import argparse
import threading

from threading import Thread, Lock
from pprint import pprint

from termcolor import colored

import targetPages

def get_args():
    parser = argparse.ArgumentParser(description='knock before you enter.')
    parser.add_argument('accounts', metavar='N', type=str, nargs='+',
                        help='account you\'d like to check')
    return parser.parse_args()

def job_check_and_print(page):
    result = page.check_result(accounts_to_test)

    print_lock.acquire()

    print('')
    print(page.site_name)
    print('=====')
    for r in result:
        text = "%s: %s" % (
                r[0],
                colored('True', 'green') if r[1] else colored('False', 'red'))

        print(text)

    print_lock.release()

print_lock = Lock()
thread_handlers = []
args = get_args()
accounts_to_test = args.accounts

thread_handlers = list(
        map(lambda page: Thread(target=job_check_and_print, args=(page,)),
            targetPages.all_pages)
        )

for handler in thread_handlers:
    handler.start()

for handler in thread_handlers:
    handler.join()
